name: optlibport

on: workflow_dispatch

jobs:
  build:
    name: Optlibport
    runs-on: ubuntu-latest
    steps:
      - name: clean up working directory
        run: rm -rf *

      - name: clean up elan
        run: rm -rf $HOME/.elan

      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: install mathlibtools
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          source ~/.profile
          pipx install mathlibtools

      - uses: actions/checkout@v2

      - name: build mathport
        run: lake build

      - name: prepare sources
        run: make mathbin-source lean3-source optlib-source

      - name: download mathbin release
        run: |
          TAG="nightly-2023-01-02-04"
          ./download-release.sh $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: make predata for optlib
        run: env time -v make optlib-predata

      - name: run mathport on optlib
        run: env time -v make port-optlib

      - name: prepare tarballs for release
        run: make optlib-tarballs

      - name: set tag
        run: echo "TAG=port-$(date -u +%F)" >> $GITHUB_ENV && echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ env.TAG }}-${{ env.SHORT_SHA }}
          target_commitish: ${{ github.sha }}
          files: |
            optlib-binport.tar.gz
            optlib-synport.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: clean up working directory
        run: rm -rf *

      - name: clean up elan
        run: rm -rf $HOME/.elan
