name: mathport

on: workflow_dispatch

jobs:
  build:
    name: Mathport
    runs-on: ubuntu-latest
    steps:
      - name: clean up working directory
        run: rm -rf *

      - name: clean up elan
        run: rm -rf $HOME/.elan

      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.3.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2

      - name: build mathport
        run: make build

      - name: prepare sources
        run: make mathbin-source lean3-source

      - name: prepare predata for Lean 3
        run: make lean3-predata

      - name: prepare predata for mathlib
        run: make mathbin-predata

      - name: run mathport on Lean 3
        run: env time -v make port-lean

      - name: run mathport on mathlib
        run: env time -v make port-mathbin

      - name: prepare tarballs for release
        run: make mathport-tarballs

      - name: set tag (non-master)
        if: github.ref != 'refs/heads/master'
        run: echo "TAG=pr-${GITHUB_REF##*/}" >> $GITHUB_ENV && echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: set tag (master)
        if: github.ref == 'refs/heads/master'
        run: echo "TAG=nightly-$(date -u +%F)" >> $GITHUB_ENV

      - name: release (non-master)
        if: github.ref != 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ env.TAG }}-${{ env.SHORT_SHA }}
          target_commitish: ${{ github.sha }}
          files: |
            lean3-binport.tar.gz
            lean3-synport.tar.gz
            mathlib3-binport.tar.gz
            mathlib3-synport.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release (master)
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ env.TAG }}
          target_commitish: ${{ github.sha }}
          files: |
            lean3-binport.tar.gz
            lean3-synport.tar.gz
            mathlib3-binport.tar.gz
            mathlib3-synport.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: clean up working directory
        run: rm -rf *

      - name: clean up elan
        run: rm -rf $HOME/.elan
